# Generated by Django 4.0.4 on 2022-04-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipoUsuario',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
