# Generated by Django 4.0.4 on 2022-04-21 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_tipousuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='Producto',
        ),
    ]
