# Generated by Django 4.0.2 on 2022-04-22 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_produto_producto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserComplex',
        ),
    ]
