# Generated by Django 4.0.4 on 2022-05-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_usercomplex_password_usercomplex_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomplex',
            name='QR',
            field=models.CharField(max_length=50),
        ),
    ]
