# Generated by Django 4.0.4 on 2022-05-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_usercomplex_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomplex',
            name='residencia',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
